#!/usr/bin/env python3

'''
$ smon
             -------pending-------   -------running-------   ------completing-----
             mem(GB)  #cpus  #jobs   mem(GB)  #cpus  #jobs   mem(GB)  #cpus  #jobs
[username]    10690   5345   5345      2046   1023   1023
[username]      234    480     60        64     69     27
[username]                               19     60      5
[username]        9      2      2        46     48     12
[username]     1453    744    744         1      1      1        11      6      6
[username]      114     39     39                                 2      1      1
[username]    72186   2858   2858

CPUS ON CLUSTER:
 allocated: 3951
      idle: 3188
     other:  541
     total: 7680
'''

from subprocess import check_output
from collections import Counter
from math import floor, ceil

states = 'PD R CG'.split()
o = check_output('squeue --array --Format=username:15,statecompact:3,numcpus:5,minmemory:10'.split()).decode('ascii').rstrip('\n').split('\n')
assert o[0] == '{:15}{:3}{:5}{:10}'.format('USER','ST','CPUS','MIN_MEMORY'), o[0]
ppl = {}
for line in o[1:]:
    try:
        username, state, ncpus, mem = line[0:15].strip(), line[15:18].strip(), int(line[18:23]), line[23:33].strip()
        assert state in states, state
        if mem.isdigit(): mem = int(mem) / 1024
        elif mem.endswith('K'): mem = int(mem[:-1])
        else: raise mem
        ppl.setdefault(username, {}).setdefault('jobs', Counter())[state] += 1
        ppl.setdefault(username, {}).setdefault('cpus', Counter())[state] += ncpus
        ppl.setdefault(username, {}).setdefault('mem', Counter())[state] += mem
    except Exception as exc: raise Eception('BAD LINE: ' + repr(line)) from exc
print(' '*13+'-------pending-------   -------running-------   ------completing-----')
print(' '*13+'mem(GB)  #cpus  #jobs   mem(GB)  #cpus  #jobs   mem(GB)  #cpus  #jobs')
for username in sorted(ppl.keys(), key=lambda u: -ppl[u]['cpus']['R']):
    for state in states: ppl[username]['mem'][state] = int(ppl[username]['mem'][state])
    print('{:12}{:7}{:7}{:7}   {:7}{:7}{:7}   {:7}{:7}{:7}'.format(
        username,
        *[ppl[username][metric][state] or '' for state in states for metric in ['mem','cpus','jobs']]
    ))
print('\n')


print('CPUS ON CLUSTER:')
o = check_output('sinfo --format=%C'.split()).decode('ascii').split('\n')
assert o[0] == 'CPUS(A/I/O/T)'
for label, ncpus in zip('allocated idle other total'.split(), [int(x) for x in o[1].split('/')]):
    print('{:>10}:{:5}'.format(label, ncpus))
